version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Tokyo
    commit-message:
      prefix: ci
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Tokyo
    commit-message:
      prefix: deps
    allow:
      - dependency-type: all
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
    groups:
      nuget-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
